from typing import Any
def cityblock(u: Any, v: Any, w: Any = ...) -> float: ...
def cosine(u: Any, v: Any, w: Any = ...) -> float: ...
def euclidean(u: Any, v: Any, w: Any = ...) -> float: ...
def hamming(u: Any, v: Any, w: Any = ...) -> float: ...
def sqeuclidean(u: Any, v: Any, w: Any = ...) -> float: ...
