"""Fusion method #4 — resolve the dataflow leg's *dispatch wall* with the shared tool model.

The dataflow leg (``taint_engine``) follows taint along concrete code paths, but a
*dynamic-dispatch* site — ``TOOL_MAP[name](**args)``, ``get_function(name)(...)``,
``getattr(mod, name)(...)`` — has a runtime-selected callee, so a static analysis
cannot say which concrete tool (hence which sink) the (control-tainted) arguments
reach. The engine localises this precisely: it records a ``kind="dispatch"``
:class:`~ctaudit.report.Finding` *only* when control taint actually reaches the site,
carrying the path context the enumeration leg lacks — the source marks on that path,
the LLM nodes (`exit_sites`) the control taint passed through, CFG reachability, and
any guard at the dispatch site.

Fusion #4 takes that localised-but-unresolved finding and the shared
:class:`~ctaudit.toolmodel.schema.RepoToolModel` (auto-generated by the #5 classifier)
and *resolves* the concrete target set, then emits one resolved flow per reachable
**sink** tool — concrete, named, guarded — instead of an opaque ``dispatch?`` node.

Target NARROWING (precision, recall-first)
------------------------------------------
A dispatch reads a specific registry, e.g. ``TOOL_MAP[name]``. When ``repo`` is given
and that registry is a **single static dict literal that is never mutated**, its
membership is *complete*, so the dispatch can only reach the tools registered in it —
the resolver narrows the target set to ``sinks ∩ registry-members`` (dropping sinks
that live in a *different* registry). If the registry can't be confidently mapped
(dynamic population, ``getattr``/higher-order callee, mutations, non-literal members)
the resolver falls back to the repo-global sink set — never dropping a sink it isn't
sure about. Guards come from the deterministic tool model; nothing is invented here.
"""
from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import List, Optional

from ..report import Finding
from ..toolmodel.schema import CATEGORY_TO_SEVERITY, RepoToolModel

_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_.]*$")


def _severity_for(t) -> str:
    """Severity for a resolved sink tool, with the 方向C reachability adjustment.

    If intra-tool analysis proved the tool's argument does NOT reach the dangerous
    call (``arg_reaches == "not"``), the finding is kept (recall-first) but
    downgraded to ``"low"`` — the dispatched value cannot drive the dangerous op, so
    it is very likely a false positive of the body-scan over-approximation.  Any
    other verdict ("reaches" / "unknown" / unanalysed) keeps the category severity.
    """
    base = CATEGORY_TO_SEVERITY.get(t.sink.category, "high") if t.sink else "high"
    if t.sink is not None and getattr(t.sink, "arg_reaches", None) == "not":
        return "low"
    return base


def _final(node) -> Optional[str]:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def _registry_name(sink_name: str) -> Optional[str]:
    """The registry variable a subscript-dispatch reads, e.g. ``TOOL_MAP[…]`` -> ``TOOL_MAP``.

    Returns None for higher-order callees (``get_function(name)(…)``) — there is no
    statically-named registry to narrow by, so the caller stays repo-global.
    """
    if not sink_name or "[" not in sink_name:
        return None
    head = sink_name.split("[", 1)[0].strip()
    if not _IDENT.match(head):
        return None
    return head.split(".")[-1]


def _split_site(site: str):
    """Split a classifier provenance site ``"path.py:line[:col]"`` into
    ``(file, "line[:col]")``; for a bare ``"line:col"`` (the engine's convention, relative
    to the finding's file) return ``(None, site)`` so the renderer doesn't double the path."""
    m = re.match(r"^(?P<f>.+\.py):(?P<rest>\d+(?::\d+)?)$", site or "")
    if m:
        return m.group("f"), m.group("rest")
    return None, site


def _dict_member_tokens(d: ast.Dict):
    """(tokens, ok) for a dict literal. ``ok`` is False if any key/value is not statically
    resolvable, so the registry must NOT be trusted for narrowing (recall-first)."""
    toks, ok = set(), True
    for k, v in zip(d.keys, d.values):
        if isinstance(k, ast.Constant) and isinstance(k.value, str):
            toks.add(k.value)
        elif k is not None:
            ok = False                      # non-string / computed key -> can't trust membership
        vn = _final(v)
        if vn:
            toks.add(vn)
        elif isinstance(v, ast.Constant) and isinstance(v.value, str):
            toks.add(v.value)
        else:
            ok = False                      # value not a plain name/attr/str -> unresolvable member
    return toks, ok


def _index_registries(repo: str):
    """name -> frozenset(member tokens) for registries that are a SINGLE static dict
    literal with no later mutation. Mutated / dynamically-built / non-literal registries
    are omitted so the caller falls back to the (conservative) repo-global sink set."""
    defs = {}            # name -> set(tokens)
    untrusted = set()    # names that are mutated or not a clean static literal
    root = Path(repo)
    pys = [root] if root.is_file() else root.rglob("*.py")
    for py in pys:
        if py.suffix != ".py":
            continue
        if any(p in (".venv", "site-packages", "tests", "test") for p in py.parts):
            continue
        try:
            tree = ast.parse(py.read_text(encoding="utf-8"))
        except Exception:
            continue
        for n in ast.walk(tree):
            if isinstance(n, ast.Assign) and len(n.targets) == 1:
                tgt = n.targets[0]
                if isinstance(tgt, ast.Name):
                    if isinstance(n.value, ast.Dict):
                        toks, ok = _dict_member_tokens(n.value)
                        if tgt.id in defs or not ok:
                            untrusted.add(tgt.id)        # 2nd def or unresolvable members
                        else:
                            defs[tgt.id] = toks
                    elif tgt.id in defs:
                        untrusted.add(tgt.id)            # rebound to a non-dict
                elif isinstance(tgt, ast.Subscript) and isinstance(tgt.value, ast.Name):
                    untrusted.add(tgt.value.id)          # REGISTRY[k] = ... mutation
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute) and \
               isinstance(n.func.value, ast.Name) and \
               n.func.attr in ("update", "setdefault", "__setitem__", "pop", "popitem", "clear"):
                untrusted.add(n.func.value.id)           # REGISTRY.update(...) mutation
    return {k: frozenset(v) for k, v in defs.items() if k not in untrusted and v}


def _tool_in_members(t, members) -> bool:
    if t.name in members:
        return True
    if t.callable:
        return t.callable in members or t.callable.split(".")[-1] in members
    return False


# ---- phase / tool-name whitelist gate (codecli PHASE_TOOLS shape) ---------- #
#
# Many agents gate a dispatch by a tool-name whitelist before running it, e.g.
#
#     allowed = PHASE_TOOLS.get(phase, [])          # PHASE_TOOLS: dict[..., list[str]]
#     if name not in allowed:                        # <- membership gate on the dispatch key
#         continue
#     TOOL_MAP[name](**args)                          # <- dispatch
#
# A tool whose name is in no whitelist value is provably rejected by the gate, so it
# cannot be reached through this dispatch. When the gate dominates the dispatch and
# checks the *same key variable* the dispatch indexes with, we intersect the targets
# with the union of the whitelist's members (sound, recall-first). Per-phase narrowing
# would need phase-state tracking; the union is the safe static over-approximation.

def _str_seq_members(node):
    """{str, ...} for a List/Tuple/Set of string constants, else None."""
    if isinstance(node, (ast.List, ast.Tuple, ast.Set)):
        out = set()
        for e in node.elts:
            if isinstance(e, ast.Constant) and isinstance(e.value, str):
                out.add(e.value)
            else:
                return None
        return out
    return None


def _index_name_whitelists(repo: str):
    """name -> frozenset(tool-name strings) for trusted, unmutated whitelists:
    a dict whose values are all string-sequences (PHASE_TOOLS: union of all values),
    or a flat string-sequence bound to a NAME."""
    defs, untrusted = {}, set()
    root = Path(repo)
    pys = [root] if root.is_file() else root.rglob("*.py")
    for py in pys:
        if py.suffix != ".py":
            continue
        if any(p in (".venv", "site-packages", "tests", "test") for p in py.parts):
            continue
        try:
            tree = ast.parse(py.read_text(encoding="utf-8"))
        except Exception:
            continue
        for n in ast.walk(tree):
            if isinstance(n, ast.Assign) and len(n.targets) == 1 and isinstance(n.targets[0], ast.Name):
                nm = n.targets[0].id
                members = None
                if isinstance(n.value, ast.Dict) and n.value.values:
                    vals, ok = set(), True
                    for v in n.value.values:
                        m = _str_seq_members(v)
                        if m is None:
                            ok = False
                            break
                        vals |= m
                    members = vals if ok else None
                else:
                    members = _str_seq_members(n.value)
                if members is not None:
                    if nm in defs:
                        untrusted.add(nm)
                    else:
                        defs[nm] = members
                elif nm in defs:
                    untrusted.add(nm)
            elif isinstance(n, ast.Assign):
                for t in n.targets:
                    if isinstance(t, ast.Subscript) and isinstance(t.value, ast.Name):
                        untrusted.add(t.value.id)              # WL[k] = ... mutation
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute) and \
               isinstance(n.func.value, ast.Name) and n.func.attr in (
                   "append", "extend", "update", "add", "setdefault", "insert",
                   "pop", "remove", "clear", "__setitem__"):
                untrusted.add(n.func.value.id)                 # WL.append(...) etc. mutation
    return {k: frozenset(v) for k, v in defs.items() if k not in untrusted and v}


def _enclosing_func(tree, line):
    best = None
    for n in ast.walk(tree):
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if n.lineno <= line <= getattr(n, "end_lineno", n.lineno):
                if best is None or n.lineno > best.lineno:
                    best = n
    return best


def _subscript_key_name(call):
    sl = call.func.slice
    if isinstance(sl, ast.Index):           # py<3.9
        sl = sl.value
    return sl.id if isinstance(sl, ast.Name) else None


def _dispatch_key_var(func, line):
    for n in ast.walk(func):
        if isinstance(n, ast.Call) and getattr(n, "lineno", None) == line and \
           isinstance(n.func, ast.Subscript):
            return _subscript_key_name(n)
    return None


def _alias_wl(value, whitelists):
    """WL name if `value` resolves to a whitelist (WL, WL.get(...), WL[...])."""
    if isinstance(value, ast.Name) and value.id in whitelists:
        return value.id
    if isinstance(value, ast.Subscript) and isinstance(value.value, ast.Name) and value.value.id in whitelists:
        return value.value.id
    if isinstance(value, ast.Call) and isinstance(value.func, ast.Attribute) and \
       isinstance(value.func.value, ast.Name) and value.func.value.id in whitelists and \
       value.func.attr in ("get", "values"):
        return value.func.value.id
    return None


def _build_aliases(func, whitelists):
    aliases = {}
    for n in ast.walk(func):
        if isinstance(n, ast.Assign) and len(n.targets) == 1 and isinstance(n.targets[0], ast.Name):
            wl = _alias_wl(n.value, whitelists)
            if wl:
                aliases[n.targets[0].id] = wl
    return aliases


def _resolve_wl(node, whitelists, aliases):
    nm = None
    if isinstance(node, ast.Name):
        nm = node.id if node.id in whitelists else aliases.get(node.id)
    elif isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
        nm = node.value.id if node.value.id in whitelists else aliases.get(node.value.id)
    elif isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and \
         isinstance(node.func.value, ast.Name) and node.func.attr in ("get", "values"):
        base = node.func.value.id
        nm = base if base in whitelists else aliases.get(base)
    return whitelists.get(nm) if nm else None


def _has_early_exit(body):
    return any(isinstance(s, (ast.Return, ast.Raise, ast.Continue, ast.Break)) for s in body)


def _whitelist_gate_members(repo: str, finding: Finding, whitelists):
    """Member set if the dispatch's enclosing function gates the dispatch's *key variable*
    with a dominating membership check against a trusted whitelist; else None."""
    if not whitelists:
        return None
    fpath = finding.file
    if not fpath or not Path(fpath).is_file():
        return None
    try:
        tree = ast.parse(Path(fpath).read_text(encoding="utf-8"))
        line = int(str(finding.sink_site).split(":")[0])
    except Exception:
        return None
    func = _enclosing_func(tree, line)
    if func is None:
        return None
    key_var = _dispatch_key_var(func, line)
    if key_var is None:
        return None
    aliases = _build_aliases(func, whitelists)
    for n in ast.walk(func):
        if not isinstance(n, ast.If):
            continue
        test = n.test
        if not (isinstance(test, ast.Compare) and len(test.ops) == 1 and
                isinstance(test.left, ast.Name) and test.left.id == key_var):
            continue
        wl = _resolve_wl(test.comparators[0], whitelists, aliases)
        if wl is None:
            continue
        op = test.ops[0]
        if isinstance(op, ast.NotIn) and _has_early_exit(n.body) and n.lineno < line:
            return wl                              # `if key not in WL: <exit>` before dispatch
        if isinstance(op, ast.In) and n.body and \
           n.body[0].lineno <= line <= getattr(n, "end_lineno", n.lineno):
            return wl                              # dispatch nested under `if key in WL:`
    return None


def _emit_targets(f: Finding, targets, keep_unresolved: bool, out: List[Finding],
                  evidence_backed: bool) -> None:
    """Emit one resolved Finding per target sink, preserving the wall's provenance.

    Shared by the framework-managed dispatch path (項目1) and mirrors the
    syntactic-wall emission below.  ``evidence_backed`` says whether the empty-target
    case is backed by trusted membership (emit nothing) or not (keep the wall).
    """
    if not targets:
        if evidence_backed:
            return  # provably reaches no sink -> emit nothing (precise, recall-safe)
        if keep_unresolved:
            out.append(f)
        return
    kind = "implicit" if f.source_marks else "explicit"
    for t in targets:
        cat = t.sink.category
        tfile, tsite = (f.file or ""), f.sink_site
        if t.site:
            pf, ps = _split_site(t.site)
            tfile, tsite = (pf or tfile), ps
        out.append(Finding(
            kind=kind,
            sink_name=t.name,
            sink_category=cat,
            severity=_severity_for(t),
            sink_site=tsite,
            arg_expr=f.arg_expr,
            param_type="string",
            source_marks=f.source_marks,
            exit_sites=f.exit_sites,
            file=tfile,
            reachable=f.reachable,
            guard=(t.sink.guard or f.guard),
            via_dispatch=f.sink_name,
            framework_candidates=f.framework_candidates,
        ))


def resolve_dispatch(findings: List[Finding], model: RepoToolModel,
                     repo: Optional[str] = None,
                     keep_unresolved: bool = True,
                     framework_registry_trust: bool = False) -> List[Finding]:
    """Resolve each dispatch wall to the model's concrete sinks (narrowed by registry).

    Non-dispatch findings pass through unchanged. A ``kind="dispatch"`` finding becomes
    one resolved finding per reachable sink tool. With ``repo`` given, the target set is
    narrowed (1) to the sinks registered in the dispatch's registry when that registry is
    a trusted static literal, and (2) to the union of a tool-name whitelist when the
    dispatch's key variable is gated by a dominating membership check against one (e.g.
    codecli's ``PHASE_TOOLS``); otherwise the repo-global sink set is used. If the model
    has no sinks (or the dispatch provably reaches none) nothing false is emitted; an
    unresolvable wall is kept when ``keep_unresolved``.

    ``framework_registry_trust`` (項目1) controls how a *framework-managed* dispatch's
    registered tool set (``Finding.framework_candidates``, from create_react_agent(
    tools=[...]) etc.) is used:

    * ``False`` (default, conservative / recall-first): the registered set is treated as
      *candidates only* and does NOT narrow — every dangerous sink the model knows is kept
      as a target, so a tool the framework could reach is never dropped on the strength of
      a registration list alone.
    * ``True``: the registered set is trusted as complete membership (like a static
      registry literal) and the targets are narrowed to its intersection with the sinks.
    """
    sinks = [t for t in model.tools if t.sink]
    registries = _index_registries(repo) if repo else {}
    whitelists = _index_name_whitelists(repo) if repo else {}
    out: List[Finding] = []
    for f in findings:
        if f.kind != "dispatch":
            out.append(f)
            continue
        if not sinks:
            if keep_unresolved:
                out.append(f)
            continue
        # 項目1: framework-managed dispatch carries its registered tool set.
        fw_cands = getattr(f, "framework_candidates", ()) or ()
        if fw_cands:
            if framework_registry_trust:
                # trust the registration as complete membership -> narrow.
                targets = [t for t in sinks if _tool_in_members(t, set(fw_cands))]
            else:
                # conservative: candidates only, do not narrow (recall-first).
                targets = sinks
            targets = _emit_targets(f, targets, keep_unresolved, out,
                                    evidence_backed=framework_registry_trust)
            continue
        reg = _registry_name(f.sink_name)
        members = registries.get(reg) if reg else None
        if members is not None:                       # trusted, complete membership
            targets = [t for t in sinks if _tool_in_members(t, members)]
        else:                                         # can't map the registry -> conservative
            targets = sinks
        # phase / tool-name whitelist gate (further narrowing, sound)
        gate_applied = False
        if whitelists:
            gate = _whitelist_gate_members(repo, f, whitelists)
            if gate is not None:
                gate_applied = True
                targets = [t for t in targets
                           if t.name in gate or (t.callable and t.callable.split(".")[-1] in gate)]
        if not targets:
            # membership/gate is known and no sink survives: the dispatch provably reaches
            # no sink -> emit nothing (precise & recall-safe). Otherwise keep the wall.
            if members is not None or gate_applied:
                continue
            if keep_unresolved:
                out.append(f)
            continue
        kind = "implicit" if f.source_marks else "explicit"   # dispatch is recorded under control taint
        for t in targets:
            cat = t.sink.category
            tfile, tsite = (f.file or model.repo), f.sink_site
            if t.site:                                   # classifier site may be "path.py:line[:col]"
                pf, ps = _split_site(t.site)
                tfile, tsite = (pf or tfile), ps
            out.append(Finding(
                kind=kind,
                sink_name=t.name,
                sink_category=cat,                       # lowercase, same vocab as the engine
                severity=_severity_for(t),
                sink_site=tsite,
                arg_expr=f.arg_expr,                     # the dispatch expression
                param_type="string",
                source_marks=f.source_marks,             # PRESERVE the path's sources
                exit_sites=f.exit_sites,                 # PRESERVE the LLM nodes on the path
                file=tfile,
                reachable=f.reachable,
                guard=(t.sink.guard or f.guard),         # deterministic guard; never invented
                via_dispatch=f.sink_name,                # the dispatch expr we resolved from
            ))
    return out
