#!/usr/bin/env python3
"""Generate FULL AgentDojo runtime fixtures (all tools of each suite) from the
real SOURCES/SINKS metadata in corpus/agentdojo/analyze_<suite>.py.

Unlike the reduced agentdojo_<suite>_runtime.py fixtures (a handful of tools, no
over-flagging), these expand EVERY source and sink the suite registers into the
``TOOLS`` list behind the same ``run_function`` dict-registry wall. Resolving the
wall then produces the full source×sink candidate space — including over-flags —
so a single --compare-stages run shows resolution AND pruning AND triage effects
in one progression.

Run:  python gen_agentdojo_full_fixtures.py
Emits: fixtures/agentdojo_<suite>_full.py for each suite.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CORPUS = ROOT / "corpus" / "agentdojo"
SUITES = ("banking", "workspace", "travel", "slack")


def _load(suite):
    sys.path.insert(0, str(CORPUS))
    spec = importlib.util.spec_from_file_location(
        f"_ad_{suite}", str(CORPUS / f"analyze_{suite}.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_HEADER = '''"""VULNERABLE — AgentDojo {suite} runtime, FULL tool registry (auto-generated).

Every source and sink the AgentDojo '{suite}' suite registers is expanded into
the TOOLS list behind the same run_function dict-registry wall, so resolving the
wall yields the full source×sink candidate space (including over-flags). This
lets one --compare-stages run show resolution → over-flag → pruning → triage.

Generated by gen_agentdojo_full_fixtures.py from corpus/agentdojo/analyze_{suite}.py.
This file is an analysis target only; it is never executed.
"""

from typing import Annotated

from openai import OpenAI

'''


def _src_fn(name: str) -> str:
    return (f'def {name}(env: Annotated[object, "env"], query: str = "") -> str:\n'
            f'    """UNTRUSTED environment data → tool-output source."""\n'
            f'    return env.read("{name}", query)\n\n')


def _sink_fn(name: str, arg: str) -> str:
    arg = arg or "payload"
    return (f'def {name}(env: Annotated[object, "env"], {arg}: str) -> dict:\n'
            f'    """DANGEROUS domain sink."""\n'
            f'    return env.act("{name}", {arg})\n\n')


_RUNTIME = '''
class FunctionsRuntime:
    def __init__(self, functions):
        self.functions = {f.__name__: f for f in functions}

    def run_function(self, env, function: str, kwargs):
        f = self.functions[function]          # dict-registry lookup (LLM-chosen name)
        return f(**kwargs), None              # the dispatch wall (indirected via f)


def run_agent(query: str):
    runtime = FunctionsRuntime(TOOLS)
    client = OpenAI()
    messages = [{"role": "user", "content": query}]
    for _ in range(15):
        resp = client.chat.completions.create(messages=messages, model="gpt-4o")
        tool_calls = resp.choices[0].message.tool_calls
        if not tool_calls:
            break
        for tc in tool_calls:
            runtime.run_function(None, tc.function.name, tc.function.arguments)
    return messages[-1]["content"]
'''


def generate(suite: str) -> str:
    mod = _load(suite)
    parts = [_HEADER.format(suite=suite)]
    names = []
    # sources first, then sinks; skip names that are both (keep as source fn)
    seen = set()
    for name in mod.SOURCES:
        if name in seen:
            continue
        seen.add(name)
        parts.append(_src_fn(name))
        names.append(name)
    for name, meta in mod.SINKS.items():
        if name in seen:
            continue
        seen.add(name)
        parts.append(_sink_fn(name, meta.get("arg")))
        names.append(name)
    parts.append("TOOLS = [\n    " +
                 ",\n    ".join(names) + ",\n]\n")
    parts.append(_RUNTIME)
    return "".join(parts)


def main() -> int:
    out_dir = ROOT / "fixtures"
    for suite in SUITES:
        code = generate(suite)
        path = out_dir / f"agentdojo_{suite}_full.py"
        path.write_text(code)
        n = code.count("\ndef ") - 1  # minus run_agent
        print(f"  wrote {path}  ({n} tool fn(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
