from typing import Any
class Response:
    def json(self) -> Any: ...
class Client:
    def post(self, url: str, *, json: Any = ..., **kwargs: Any) -> Response: ...
    def __init__(self, *a: Any, **k: Any) -> None: ...
