"""VULNERABLE — AgentDojo workspace runtime, FULL tool registry (auto-generated).

Every source and sink the AgentDojo 'workspace' suite registers is expanded into
the TOOLS list behind the same run_function dict-registry wall, so resolving the
wall yields the full source×sink candidate space (including over-flags). This
lets one --compare-stages run show resolution → over-flag → pruning → triage.

Generated by gen_agentdojo_full_fixtures.py from corpus/agentdojo/analyze_workspace.py.
This file is an analysis target only; it is never executed.
"""

from typing import Annotated

from openai import OpenAI

def get_received_emails(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_received_emails", query)

def get_unread_emails(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_unread_emails", query)

def search_emails(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("search_emails", query)

def get_sent_emails(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_sent_emails", query)

def get_draft_emails(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_draft_emails", query)

def search_contacts_by_name(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("search_contacts_by_name", query)

def search_contacts_by_email(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("search_contacts_by_email", query)

def search_calendar_events(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("search_calendar_events", query)

def get_day_calendar_events(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_day_calendar_events", query)

def get_current_day(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_current_day", query)

def list_files(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("list_files", query)

def get_file_by_id(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_file_by_id", query)

def search_files(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("search_files", query)

def search_files_by_filename(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("search_files_by_filename", query)

def send_email(env: Annotated[object, "env"], recipients: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("send_email", recipients)

def delete_email(env: Annotated[object, "env"], email_id: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("delete_email", email_id)

def create_calendar_event(env: Annotated[object, "env"], participants: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("create_calendar_event", participants)

def add_calendar_event_participants(env: Annotated[object, "env"], participants: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("add_calendar_event_participants", participants)

def cancel_calendar_event(env: Annotated[object, "env"], event_id: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("cancel_calendar_event", event_id)

def reschedule_calendar_event(env: Annotated[object, "env"], new_start_time: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("reschedule_calendar_event", new_start_time)

def share_file(env: Annotated[object, "env"], email: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("share_file", email)

def delete_file(env: Annotated[object, "env"], file_id: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("delete_file", file_id)

def create_file(env: Annotated[object, "env"], content: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("create_file", content)

def append_to_file(env: Annotated[object, "env"], content: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("append_to_file", content)

TOOLS = [
    get_received_emails,
    get_unread_emails,
    search_emails,
    get_sent_emails,
    get_draft_emails,
    search_contacts_by_name,
    search_contacts_by_email,
    search_calendar_events,
    get_day_calendar_events,
    get_current_day,
    list_files,
    get_file_by_id,
    search_files,
    search_files_by_filename,
    send_email,
    delete_email,
    create_calendar_event,
    add_calendar_event_participants,
    cancel_calendar_event,
    reschedule_calendar_event,
    share_file,
    delete_file,
    create_file,
    append_to_file,
]

class FunctionsRuntime:
    def __init__(self, functions):
        self.functions = {f.__name__: f for f in functions}

    def run_function(self, env, function: str, kwargs):
        f = self.functions[function]          # dict-registry lookup (LLM-chosen name)
        return f(**kwargs), None              # the dispatch wall (indirected via f)


def run_agent(query: str):
    runtime = FunctionsRuntime(TOOLS)
    client = OpenAI()
    messages = [{"role": "user", "content": query}]
    for _ in range(15):
        resp = client.chat.completions.create(messages=messages, model="gpt-4o")
        tool_calls = resp.choices[0].message.tool_calls
        if not tool_calls:
            break
        for tc in tool_calls:
            runtime.run_function(None, tc.function.name, tc.function.arguments)
    return messages[-1]["content"]
