"""VULNERABLE — AgentDojo slack runtime, FULL tool registry (auto-generated).

Every source and sink the AgentDojo 'slack' suite registers is expanded into
the TOOLS list behind the same run_function dict-registry wall, so resolving the
wall yields the full source×sink candidate space (including over-flags). This
lets one --compare-stages run show resolution → over-flag → pruning → triage.

Generated by gen_agentdojo_full_fixtures.py from corpus/agentdojo/analyze_slack.py.
This file is an analysis target only; it is never executed.
"""

from typing import Annotated

from openai import OpenAI

def read_channel_messages(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("read_channel_messages", query)

def read_inbox(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("read_inbox", query)

def get_webpage(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_webpage", query)

def get_channels(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_channels", query)

def get_users_in_channel(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_users_in_channel", query)

def send_direct_message(env: Annotated[object, "env"], recipient: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("send_direct_message", recipient)

def send_channel_message(env: Annotated[object, "env"], channel: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("send_channel_message", channel)

def post_webpage(env: Annotated[object, "env"], content: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("post_webpage", content)

def invite_user_to_slack(env: Annotated[object, "env"], user_email: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("invite_user_to_slack", user_email)

def add_user_to_channel(env: Annotated[object, "env"], user: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("add_user_to_channel", user)

def remove_user_from_slack(env: Annotated[object, "env"], user: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("remove_user_from_slack", user)

TOOLS = [
    read_channel_messages,
    read_inbox,
    get_webpage,
    get_channels,
    get_users_in_channel,
    send_direct_message,
    send_channel_message,
    post_webpage,
    invite_user_to_slack,
    add_user_to_channel,
    remove_user_from_slack,
]

class FunctionsRuntime:
    def __init__(self, functions):
        self.functions = {f.__name__: f for f in functions}

    def run_function(self, env, function: str, kwargs):
        f = self.functions[function]          # dict-registry lookup (LLM-chosen name)
        return f(**kwargs), None              # the dispatch wall (indirected via f)


def run_agent(query: str):
    runtime = FunctionsRuntime(TOOLS)
    client = OpenAI()
    messages = [{"role": "user", "content": query}]
    for _ in range(15):
        resp = client.chat.completions.create(messages=messages, model="gpt-4o")
        tool_calls = resp.choices[0].message.tool_calls
        if not tool_calls:
            break
        for tc in tool_calls:
            runtime.run_function(None, tc.function.name, tc.function.arguments)
    return messages[-1]["content"]
