"""VULNERABLE — AgentDojo banking runtime, FULL tool registry (auto-generated).

Every source and sink the AgentDojo 'banking' suite registers is expanded into
the TOOLS list behind the same run_function dict-registry wall, so resolving the
wall yields the full source×sink candidate space (including over-flags). This
lets one --compare-stages run show resolution → over-flag → pruning → triage.

Generated by gen_agentdojo_full_fixtures.py from corpus/agentdojo/analyze_banking.py.
This file is an analysis target only; it is never executed.
"""

from typing import Annotated

from openai import OpenAI

def get_most_recent_transactions(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_most_recent_transactions", query)

def get_scheduled_transactions(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_scheduled_transactions", query)

def read_file(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("read_file", query)

def get_user_info(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_user_info", query)

def get_balance(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_balance", query)

def get_iban(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_iban", query)

def send_money(env: Annotated[object, "env"], recipient: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("send_money", recipient)

def schedule_transaction(env: Annotated[object, "env"], recipient: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("schedule_transaction", recipient)

def update_scheduled_transaction(env: Annotated[object, "env"], recipient: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("update_scheduled_transaction", recipient)

def update_password(env: Annotated[object, "env"], password: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("update_password", password)

def update_user_info(env: Annotated[object, "env"], street: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("update_user_info", street)

TOOLS = [
    get_most_recent_transactions,
    get_scheduled_transactions,
    read_file,
    get_user_info,
    get_balance,
    get_iban,
    send_money,
    schedule_transaction,
    update_scheduled_transaction,
    update_password,
    update_user_info,
]

class FunctionsRuntime:
    def __init__(self, functions):
        self.functions = {f.__name__: f for f in functions}

    def run_function(self, env, function: str, kwargs):
        f = self.functions[function]          # dict-registry lookup (LLM-chosen name)
        return f(**kwargs), None              # the dispatch wall (indirected via f)


def run_agent(query: str):
    runtime = FunctionsRuntime(TOOLS)
    client = OpenAI()
    messages = [{"role": "user", "content": query}]
    for _ in range(15):
        resp = client.chat.completions.create(messages=messages, model="gpt-4o")
        tool_calls = resp.choices[0].message.tool_calls
        if not tool_calls:
            break
        for tc in tool_calls:
            runtime.run_function(None, tc.function.name, tc.function.arguments)
    return messages[-1]["content"]
