"""VULNERABLE — AgentDojo travel runtime, FULL tool registry (auto-generated).

Every source and sink the AgentDojo 'travel' suite registers is expanded into
the TOOLS list behind the same run_function dict-registry wall, so resolving the
wall yields the full source×sink candidate space (including over-flags). This
lets one --compare-stages run show resolution → over-flag → pruning → triage.

Generated by gen_agentdojo_full_fixtures.py from corpus/agentdojo/analyze_travel.py.
This file is an analysis target only; it is never executed.
"""

from typing import Annotated

from openai import OpenAI

def get_rating_reviews_for_hotels(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_rating_reviews_for_hotels", query)

def get_rating_reviews_for_restaurants(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_rating_reviews_for_restaurants", query)

def get_rating_reviews_for_car_rental(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_rating_reviews_for_car_rental", query)

def search_calendar_events(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("search_calendar_events", query)

def get_day_calendar_events(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_day_calendar_events", query)

def get_user_information(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_user_information", query)

def get_all_hotels_in_city(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_all_hotels_in_city", query)

def get_hotels_address(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_hotels_address", query)

def get_all_restaurants_in_city(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_all_restaurants_in_city", query)

def get_restaurants_address(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_restaurants_address", query)

def get_contact_information_for_restaurants(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_contact_information_for_restaurants", query)

def get_all_car_rental_companies_in_city(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_all_car_rental_companies_in_city", query)

def get_car_rental_address(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_car_rental_address", query)

def get_hotels_prices(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_hotels_prices", query)

def get_price_for_restaurants(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_price_for_restaurants", query)

def get_car_price_per_day(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_car_price_per_day", query)

def get_cuisine_type_for_restaurants(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_cuisine_type_for_restaurants", query)

def get_dietary_restrictions_for_all_restaurants(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_dietary_restrictions_for_all_restaurants", query)

def check_restaurant_opening_hours(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("check_restaurant_opening_hours", query)

def get_car_types_available(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_car_types_available", query)

def get_car_fuel_options(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_car_fuel_options", query)

def get_flight_information(env: Annotated[object, "env"], query: str = "") -> str:
    """UNTRUSTED environment data → tool-output source."""
    return env.read("get_flight_information", query)

def reserve_hotel(env: Annotated[object, "env"], hotel: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("reserve_hotel", hotel)

def reserve_restaurant(env: Annotated[object, "env"], restaurant: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("reserve_restaurant", restaurant)

def reserve_car_rental(env: Annotated[object, "env"], company: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("reserve_car_rental", company)

def create_calendar_event(env: Annotated[object, "env"], participants: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("create_calendar_event", participants)

def cancel_calendar_event(env: Annotated[object, "env"], event_id: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("cancel_calendar_event", event_id)

def send_email(env: Annotated[object, "env"], recipients: str) -> dict:
    """DANGEROUS domain sink."""
    return env.act("send_email", recipients)

TOOLS = [
    get_rating_reviews_for_hotels,
    get_rating_reviews_for_restaurants,
    get_rating_reviews_for_car_rental,
    search_calendar_events,
    get_day_calendar_events,
    get_user_information,
    get_all_hotels_in_city,
    get_hotels_address,
    get_all_restaurants_in_city,
    get_restaurants_address,
    get_contact_information_for_restaurants,
    get_all_car_rental_companies_in_city,
    get_car_rental_address,
    get_hotels_prices,
    get_price_for_restaurants,
    get_car_price_per_day,
    get_cuisine_type_for_restaurants,
    get_dietary_restrictions_for_all_restaurants,
    check_restaurant_opening_hours,
    get_car_types_available,
    get_car_fuel_options,
    get_flight_information,
    reserve_hotel,
    reserve_restaurant,
    reserve_car_rental,
    create_calendar_event,
    cancel_calendar_event,
    send_email,
]

class FunctionsRuntime:
    def __init__(self, functions):
        self.functions = {f.__name__: f for f in functions}

    def run_function(self, env, function: str, kwargs):
        f = self.functions[function]          # dict-registry lookup (LLM-chosen name)
        return f(**kwargs), None              # the dispatch wall (indirected via f)


def run_agent(query: str):
    runtime = FunctionsRuntime(TOOLS)
    client = OpenAI()
    messages = [{"role": "user", "content": query}]
    for _ in range(15):
        resp = client.chat.completions.create(messages=messages, model="gpt-4o")
        tool_calls = resp.choices[0].message.tool_calls
        if not tool_calls:
            break
        for tc in tool_calls:
            runtime.run_function(None, tc.function.name, tc.function.arguments)
    return messages[-1]["content"]
